#ifndef _LANGUAGES_H_
#define _LANGUAGES_H_

const char* TXT_AppVersion;
const char* MSG_GetConsoleRegion;
const char* MSG_GetSysMenuVer;
const char* MSG_GetHBCVer;
const char* MSG_GetRunningIOS;
const char* MSG_GetConsoleID;
const char* MSG_GetBoot2;
const char* MSG_Update;
const char* MSG_NoUpdate;
const char* MSG_UpdateSuccess;
const char* MSG_UpdateFail;
const char* TXT_Region;
const char* TXT_Unknown;
const char* MSG_GetNrOfTitles;
const char* ERR_GetNrOfTitles;
const char* MSG_GetTitleList;
const char* ERR_GetTitleList;
const char* ERR_GetIosTMDSize;
const char* ERR_GetIosTMD;
const char* MSG_MountSD;
const char* MSG_UnmountSD;
const char* MSG_InitFAT;
const char* ERR_InitFAT;
const char* MSG_SortTitles;
const char* MSG_GetCertificates;
const char* ERR_GetCertificates;
const char* TXT_SysMenu;
const char* TXT_SysMenu2;
const char* TXT_SysMenu3;
const char* TXT_HBF;
const char* TXT_NO_HBC;
const char* TXT_HBC;
const char* TXT_HBC_NEW;
const char* TXT_HBC_112;
const char* TXT_HBC_STUB;
const char* TXT_Hollywood;
const char* TXT_ConsoleID;
const char* TXT_ConsoleType;
const char* TXT_ShopCountry;
const char* TXT_vBoot2;
const char* TXT_NrOfTitles;
const char* TXT_NrOfIOS;
const char* TXT_AppTitle;
const char* TXT_AppIOS;
const char* ERR_AllocateMemory;
const char* ERR_OpenFile;
const char* MSG_SelectIOS;
const char* MSG_All;
const char* MSG_TestingIOS;
const char* MSG_ReloadIOS;
const char* MSG_GenerateReport;
const char* MSG_ReportSuccess;
const char* MSG_ReportError;
const char* TXT_Stub;
const char* TXT_Trucha;
const char* TXT_ES;
const char* TXT_Flash;
const char* TXT_NAND;
const char* TXT_Boot2;
const char* TXT_USB;
const char* TXT_NoPatch;
const char* TXT_Priiloader;
const char* TXT_PreFiix;
const char* BUT_HBC;
const char* BUT_Shutoff;
const char* BUT_SysMenu;
const char* BUT_Update;
const char* TXT_VersionP;
const char* TXT_DVD;
const char* TXT_NoDVD;
const char* BUT_ConfirmUpload;
const char* TXT_Upload;
const char* BUT_OK;
const char* TXT_OriginalRegion;
char TXT_ReportDate[100];
char MSG_Buffer[1024];
char MSG_Buffer2[1024];

int initLanguages(struct tm today);

#endif
