/**
 * This file was autogenerated from Checkicon.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Checkicon_h_
#define _Checkicon_h_
//---------------------------------------------------------------------------------
extern const unsigned char Checkicon[];
extern const int Checkicon_size;
//---------------------------------------------------------------------------------
#endif //_Checkicon_h_
//---------------------------------------------------------------------------------
