/**
 * This file was autogenerated from loadingbargrey.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _loadingbargrey_h_
#define _loadingbargrey_h_
//---------------------------------------------------------------------------------
extern const unsigned char loadingbargrey[];
extern const int loadingbargrey_size;
//---------------------------------------------------------------------------------
#endif //_loadingbargrey_h_
//---------------------------------------------------------------------------------
