/**
 * This file was autogenerated from loadingbarblue.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _loadingbarblue_h_
#define _loadingbarblue_h_
//---------------------------------------------------------------------------------
extern const unsigned char loadingbarblue[];
extern const int loadingbarblue_size;
//---------------------------------------------------------------------------------
#endif //_loadingbarblue_h_
//---------------------------------------------------------------------------------
