/**
 * This file was autogenerated from WiiButtonHome.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiButtonHome_h_
#define _WiiButtonHome_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiButtonHome[];
extern const int WiiButtonHome_size;
//---------------------------------------------------------------------------------
#endif //_WiiButtonHome_h_
//---------------------------------------------------------------------------------
