/**
 * This file was autogenerated from WiiButtonA.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiButtonA_h_
#define _WiiButtonA_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiButtonA[];
extern const int WiiButtonA_size;
//---------------------------------------------------------------------------------
#endif //_WiiButtonA_h_
//---------------------------------------------------------------------------------
