/**
 * This file was autogenerated from WiiButtonMinus.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiButtonMinus_h_
#define _WiiButtonMinus_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiButtonMinus[];
extern const int WiiButtonMinus_size;
//---------------------------------------------------------------------------------
#endif //_WiiButtonMinus_h_
//---------------------------------------------------------------------------------
