/**
 * This file was autogenerated from WiiDpadLeft.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiDpadLeft_h_
#define _WiiDpadLeft_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiDpadLeft[];
extern const int WiiDpadLeft_size;
//---------------------------------------------------------------------------------
#endif //_WiiDpadLeft_h_
//---------------------------------------------------------------------------------
