/**
 * This file was autogenerated from WiiDpadRight.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiDpadRight_h_
#define _WiiDpadRight_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiDpadRight[];
extern const int WiiDpadRight_size;
//---------------------------------------------------------------------------------
#endif //_WiiDpadRight_h_
//---------------------------------------------------------------------------------
