/**
 * This file was autogenerated from Deleteicon.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Deleteicon_h_
#define _Deleteicon_h_
//---------------------------------------------------------------------------------
extern const unsigned char Deleteicon[];
extern const int Deleteicon_size;
//---------------------------------------------------------------------------------
#endif //_Deleteicon_h_
//---------------------------------------------------------------------------------
