/**
 * This file was autogenerated from Refreshicon.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Refreshicon_h_
#define _Refreshicon_h_
//---------------------------------------------------------------------------------
extern const unsigned char Refreshicon[];
extern const int Refreshicon_size;
//---------------------------------------------------------------------------------
#endif //_Refreshicon_h_
//---------------------------------------------------------------------------------
