/**
 * This file was autogenerated from WiiButtonPlus.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _WiiButtonPlus_h_
#define _WiiButtonPlus_h_
//---------------------------------------------------------------------------------
extern const unsigned char WiiButtonPlus[];
extern const int WiiButtonPlus_size;
//---------------------------------------------------------------------------------
#endif //_WiiButtonPlus_h_
//---------------------------------------------------------------------------------
