#ifndef _LANGUAGES_H_
#define _LANGUAGES_H_

extern const char* TXT_AppVersion;
extern const char* MSG_GetConsoleRegion;
extern const char* MSG_GetSysMenuVer;
extern const char* MSG_GetHBCVer;
extern const char* MSG_GetRunningIOS;
extern const char* MSG_GetConsoleID;
extern const char* MSG_GetBoot2;
extern const char* MSG_Update;
extern const char* MSG_NoUpdate;
extern const char* MSG_UpdateSuccess;
extern const char* MSG_UpdateFail;
extern const char* TXT_Region;
extern const char* TXT_Unknown;
extern const char* MSG_GetNrOfTitles;
extern const char* ERR_GetNrOfTitles;
extern const char* MSG_GetTitleList;
extern const char* ERR_GetTitleList;
extern const char* ERR_GetIosTMDSize;
extern const char* ERR_GetIosTMD;
extern const char* MSG_MountSD;
extern const char* MSG_UnmountSD;
extern const char* MSG_MountUSB;
extern const char* MSG_UnmountUSB;
extern const char* MSG_InitFAT;
extern const char* ERR_InitFAT;
extern const char* MSG_SortTitles;
extern const char* MSG_GetCertificates;
extern const char* ERR_GetCertificates;
extern const char* TXT_SysMenu;
extern const char* TXT_SysMenu2;
extern const char* TXT_SysMenu3;
extern const char* TXT_HBF;
extern const char* TXT_NO_HBC;
extern const char* TXT_HBC;
extern const char* TXT_HBC_NEW;
extern const char* TXT_HBC_112;
extern const char* TXT_HBC_STUB;
extern const char* TXT_Hollywood;
extern const char* TXT_ConsoleID;
extern const char* TXT_ConsoleType;
extern const char* TXT_ShopCountry;
extern const char* TXT_vBoot2;
extern const char* TXT_NrOfTitles;
extern const char* TXT_NrOfIOS;
extern const char* TXT_AppTitle;
extern const char* TXT_AppIOS;
extern const char* ERR_AllocateMemory;
extern const char* ERR_OpenFile;
extern const char* MSG_SelectIOS;
extern const char* MSG_All;
extern const char* MSG_TestingIOS;
extern const char* MSG_ReloadIOS;
extern const char* MSG_GenerateReport;
extern const char* MSG_ReportSuccess;
extern const char* MSG_ReportError;
extern const char* TXT_Stub;
extern const char* TXT_Trucha;
extern const char* TXT_ES;
extern const char* TXT_Flash;
extern const char* TXT_NAND;
extern const char* TXT_Boot2;
extern const char* TXT_USB;
extern const char* TXT_BeerTicket;
extern const char* TXT_NoPatch;
extern const char* TXT_Priiloader;
extern const char* TXT_PreFiix;
extern const char* BUT_HBC;
extern const char* BUT_Shutoff;
extern const char* BUT_SysMenu;
extern const char* BUT_Update;
extern const char* TXT_VersionP;
extern const char* TXT_DVD;
extern const char* TXT_NoDVD;
extern const char* BUT_ConfirmUpload;
extern const char* TXT_Upload;
extern const char* BUT_OK;
extern const char* TXT_OriginalRegion;
extern const char* TXT_IOSSkipped;
extern char TXT_ReportDate[];
extern char MSG_Buffer[];
extern char MSG_Buffer2[];

int initLanguages(struct tm today);

#endif
